version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=devscale
      - POSTGRES_PASSWORD=devscale
      - POSTGRES_DB=devscale
    ports:
      - "5432:5432"
    volumes:
      - mydb-data:/var/lib/postgresql/data

volumes:
  mydb-data:
    name: mydb-data
